language: ruby
rvm:
  - 2.7
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
env:
  global:
      CC_TEST_REPORTER_ID=de078b150c6d4167c0c477e3df7afa473a5e3e37299123a917bbd9c680b7f98f
install:
  - gem install colorize
  - gem install strscan
  - gem install logger
  - gem install optparse
  - gem install simplecov -v 0.17
  - gem install rake
  - gem install test-unit
  - gem install power_assert
  - gem install json
after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 1
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
